### ISSUE TITLE
Respect custom database prefixes (and migrate data, if possible)

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-stats#2]
Currently, this plugin hardcodes `wp_` as the database prefix. It should be updated to use whatever the database prefix is for a given installation, and—if possible—should migrate `wp_` prefixed data into the new prefix.

**Comment by connerbw** [comment]
In order to activate the migration you must disable then re-enable the plugin because the code is triggered in a `register_activation_hook`
