### ISSUE TITLE
A Design Feature

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/pressbooks-stats#7]
### Prerequisites

* [ X] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-stats/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?

### Description

FEATURE
To have individual PB Statistic blocks selectable for display in the Network Admin Dashboard  > Screen Options dropdown.

**Expected behavior:
To be able to select the individual stat block, because a PB server with the same theme (EXPORTED THEME) will always be 100% and thus not necessary to view.

**Actual behavior:** [What actually happened]
View all PB stats in one window.

**Comment by greatislander** [comment]
This is a very limited use case. In our experience, most Pressbooks networks use more than one theme. If you want to add this feature you are welcomed to submit a pull request, but we won't be implementing this.
